required_resources:
   distilbert-base-uncased:  "s3://ANONYMOUS/distilbert-base-uncased"
   huggingface: "s3://ANONYMOUS/huggingface"
   emotion_splits: "s3://ANONYMOUS/emotion_splits"
remote_zoo_dir: "s3://ANONYMOUS/local_models_zoo"
load_from_zoo_use_remote: false
resource_dir: "resources"
push_to_remote_zoo: false
push_to_local_zoo: true

evolver:
  enabled: true
  with_merger: true
  f: 0.5
  # f: 0.8
  cr_max: 0.5
  cr_min: 0.5
  max_iters: 15
  resume_global: false
  save_global: true

merger:
  # regmean_exclude_param_regex: ['.*classifier.*']
  regmean_exclude_param_regex: []
  regmean_mean: true
  gram_n_example: 1000
  gram_version: "h_1000_0921_fix"
  regmean_reduce_nondiag: 0.3

# evaluate_locals_ood_after_merge: true
evaluate_locals_before: false
evaluate_locals_after: true
evaluate_global_model: false

seed: "{seed}"
main_output_dir: '/data/guodong/nlp/runs/emotion-distilbert-base-uncased/evolver-reg0.3_cr0.5_f0.5_g15/{exp_name}/seed{seed}'

default_model_args:
  model_name: "{resource_dir}/distilbert-base-uncased"
  learning_rate: 2.0e-5
  num_train_epochs: 30.0
  version: 2333
  zoo_filter:
    version: 2333
    seed: "{seed}"
    num_train_epochs: 30.0
  do_lower_case: false
  per_device_train_batch_size: 16
tokenizer: "{resource_dir}/distilbert-base-uncased"
model_type: distilbert
