required_resources:
   distilbert-base-uncased:  "s3://ANONYMOUS/distilbert-base-uncased"
   huggingface: "s3://ANONYMOUS/huggingface"
   emotion_splits: "s3://ANONYMOUS/emotion_splits"
remote_zoo_dir: "s3://ANONYMOUS/local_models_zoo"
load_from_zoo_use_remote: false
resource_dir: "resources"
push_to_remote_zoo: false
push_to_local_zoo: true

evaluate_ensemble_locals: true
# evaluate_ensemble_ood: true
# evaluate_locals_ood_after_merge: true
evaluate_locals_before: true
evaluate_locals_after: true
evaluate_individuals: true
# evaluate_individuals_ood: true

ensembler:
  enabled: true
  handle_missing_label: true

seed: "{seed}"
main_output_dir: '/data/guodong/nlp/runs/emotion-distilbert-base-uncased/simple/{exp_name}/seed{seed}'

default_model_args:
  model_name: "{resource_dir}/distilbert-base-uncased"
  learning_rate: 2.0e-5
  num_train_epochs: 30.0
  version: 2333
  zoo_filter:
    version: 2333
    seed: "{seed}"
    num_train_epochs: 30.0
  do_lower_case: false
  per_device_train_batch_size: 16
tokenizer: "{resource_dir}/distilbert-base-uncased"
model_type: distilbert
