required_resources:
   roberta-base:  "s3://ANONYMOUS/roberta-base"
   huggingface: "s3://ANONYMOUS/huggingface"
remote_zoo_dir: "s3://ANONYMOUS/local_models_zoo"
load_from_zoo_use_remote: false
resource_dir: "resources"
push_to_remote_zoo: false
push_to_local_zoo: true

evolver:
  enabled: true
  with_merger: true
  f: 0.5
  # f: 0.8
  cr_max: 0.5
  cr_min: 0.5
  max_iters: 15
  resume_global: false
  save_global: true
  evo_dataset_name: "glue"
  
merger:
  fisher_weighted: false
  regmean_mean: false

evaluate_locals_before: false
evaluate_locals_after: true
evaluate_global_model: false

seed: "{seed}"
main_output_dir: '/data/guodong/nlp/runs/glue-roberta-base/{partition_method}_1k_evolver/{dataset_name}/{seed}'

default_model_args:
  model_name: "{resource_dir}/roberta-base"
  learning_rate: 1.0e-5
  num_train_epochs: 10.0
  version: "{partition_method}1k_0"
  zoo_filter:
    version: "{partition_method}1k_0"
    seed: "{seed}"
    num_train_epochs: 10.0
  do_lower_case: true
  per_device_train_batch_size: 16
  evaluation_strategy: "steps"
  eval_steps: 500


tokenizer: "{resource_dir}/roberta-base"
model_type: roberta
