required_resources:
   distilbert-base-uncased:  "s3://ANONYMOUS/distilbert-base-uncased"
   huggingface: "s3://ANONYMOUS/huggingface"
remote_zoo_dir: "s3://ANONYMOUS/local_models_zoo"
load_from_zoo_use_remote: false
resource_dir: "resources"
push_to_remote_zoo: false
push_to_local_zoo: true

merger:
  coeff_search_method: null
  fisher_weighted: false

  # regmean_mean: true
  # gram_n_example: 1000
  # gram_version: "h_1000_0726_fix"
  exclude_param_regex: []

seed: "{seed}"
main_output_dir: 'runs/glue-distilbert-base-uncased/iid_1k/{dataset_name}/{seed}'

default_model_args:
  model_name: "{resource_dir}/distilbert-base-uncased"
  learning_rate: 2.0e-5
  num_train_epochs: 20
  version: "iid1k_0"
  zoo_filter:
    version: "iid1k_0"
    seed: "{seed}"
    num_train_epochs: 20
  do_lower_case: true
  per_device_train_batch_size: 16
  #evaluation_strategy: "steps"
  #eval_steps: 200
  #load_best_model_at_end: true
  #metric_for_best_model: "key_score"
  #save_steps: 200
  #greater_is_better: true

tokenizer: "{resource_dir}/distilbert-base-uncased"
model_type: distilbert
