required_resources:
   deberta-v3-large:  "s3://ANONYMOUS/deberta-v3-large"
   huggingface: "s3://ANONYMOUS/huggingface"
   emotion_splits: "s3://ANONYMOUS/emotion_splits"
remote_zoo_dir: "s3://ANONYMOUS/local_models_zoo"
load_from_zoo_use_remote: false
resource_dir: "resources"
push_to_remote_zoo: false
push_to_local_zoo: true
evolver:
  enabled: true
  with_merger: true
  f: 0.5
  cr_max: 0.5
  cr_min: 0.5
  max_iters: 15
  resume_global: false
  save_global: true

merger:
  fisher_weighted: true
  fisher_n_example: 1000
  fisher_version: "h_1000_fix0708"

evaluate_locals_ood_after_merge: true
evaluate_locals_before: false
evaluate_locals_after: true
evaluate_global_model: false

seed: "{seed}"
main_output_dir: '/data/guodong/nlp/runs/emotion-deberta-large/evolver-fisher_cr0.5_f0.5_g15-seed{seed}'
default_model_args:
  model_name: "{resource_dir}/deberta-v3-large"
  version: "hyp0918"
  zoo_filter:
    version: "hyp0918"
    seed: "{seed}"
  do_lower_case: false
  per_device_train_batch_size: 16
  lr_scheduler_type: "polynomial"
  warmup_ratio: 0.06
  learning_rate: 6.0e-6
  num_train_epochs: 20.0
  #adam_beta1: 0.9
  #adam_beta2: 0.98
  #adam_epsilon: 1.0e-6
  #max_grad_norm: 0.0
  save_strategy: "epoch"
  evaluation_strategy: "epoch"
  load_best_model_at_end: true
  metric_for_best_model: "key_score"
  reweight_loss_schema: "sqrt"
tokenizer: "{resource_dir}/deberta-v3-large"
model_type: deberta
