required_resources:
   roberta-base:  "s3://ANONYMOUS/roberta-base"
   huggingface: "s3://ANONYMOUS/huggingface"
remote_zoo_dir: "s3://ANONYMOUS/local_models_zoo"
load_from_zoo_use_remote: false
resource_dir: "resources"
push_to_remote_zoo: false
push_to_local_zoo: true

seed: 1
main_output_dir: 'runs/glue-roberta_base-hyp2/simple_avg'
default_model_args:
  model_name: "{resource_dir}/roberta-base"
  version: "hyp2"
  zoo_filter:
    version: "hyp2"
    seed: 1
  do_lower_case: false
  per_device_train_batch_size: 16
  lr_scheduler_type: "polynomial"
  warmup_ratio: 0.06
  learning_rate: 1.0e-5
  num_train_epochs: 10.0
  #adam_beta1: 0.9
  #adam_beta2: 0.98
  #adam_epsilon: 1.0e-6
  #max_grad_norm: 0.0
  evaluation_strategy: "epoch"
  #weight_decay: 0.1
  load_best_model_at_end: true
  metric_for_best_model: "key_score"
tokenizer: "{resource_dir}/roberta-base"
model_type: roberta-base
