required_resources:
   distilbert-base-uncased:  "s3://ANONYMOUS/distilbert-base-uncased"
   huggingface: "s3://ANONYMOUS/huggingface"
remote_zoo_dir: "s3://ANONYMOUS/local_models_zoo"
load_from_zoo_use_remote: false
resource_dir: "resources"
push_to_remote_zoo: false
push_to_local_zoo: true

merger:
  enabled: false
  exclude_param_regex: ['.*pre_classifier.*','.*classifier.*']


seed: 1
main_output_dir: 'runs/glue-distilbert-base-uncased/mtl/'
default_model_args:
  model_name: "{resource_dir}/distilbert-base-uncased"
  learning_rate: 2.0e-5
  num_train_epochs: 3.0
  version: "mtl_1"
  zoo_filter:
    version: "mtl_1"
    seed: 1
  do_lower_case: true
  per_device_train_batch_size: 16
  #max_steps: 10
tokenizer: "{resource_dir}/distilbert-base-uncased"
model_type: distilbert
